/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GetEthMarketplaceDataRequest
    /// </summary>
    [DataContract(Name = "getEthMarketplaceData_request")]
    public partial class GetEthMarketplaceDataRequest : IEquatable<GetEthMarketplaceDataRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEthMarketplaceDataRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetEthMarketplaceDataRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEthMarketplaceDataRequest" /> class.
        /// </summary>
        /// <param name="collectionAddress">Array of collection addresses (required).</param>
        /// <param name="subCollectionTags">Array of sub collections (e.g. Art Blocks).</param>
        /// <param name="normalized">Return normalized data across marketplaces.</param>
        public GetEthMarketplaceDataRequest(List<string> collectionAddress = default(List<string>), List<string> subCollectionTags = default(List<string>), bool normalized = default(bool))
        {
            // to ensure "collectionAddress" is required (not null)
            if (collectionAddress == null)
            {
                throw new ArgumentNullException("collectionAddress is a required property for GetEthMarketplaceDataRequest and cannot be null");
            }
            this.CollectionAddress = collectionAddress;
            this.SubCollectionTags = subCollectionTags;
            this.Normalized = normalized;
        }

        /// <summary>
        /// Array of collection addresses
        /// </summary>
        /// <value>Array of collection addresses</value>
        [DataMember(Name = "collection_address", IsRequired = true, EmitDefaultValue = true)]
        public List<string> CollectionAddress { get; set; }

        /// <summary>
        /// Array of sub collections (e.g. Art Blocks)
        /// </summary>
        /// <value>Array of sub collections (e.g. Art Blocks)</value>
        [DataMember(Name = "sub_collection_tags", EmitDefaultValue = false)]
        public List<string> SubCollectionTags { get; set; }

        /// <summary>
        /// Return normalized data across marketplaces
        /// </summary>
        /// <value>Return normalized data across marketplaces</value>
        [DataMember(Name = "normalized", EmitDefaultValue = true)]
        public bool Normalized { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetEthMarketplaceDataRequest {\n");
            sb.Append("  CollectionAddress: ").Append(CollectionAddress).Append("\n");
            sb.Append("  SubCollectionTags: ").Append(SubCollectionTags).Append("\n");
            sb.Append("  Normalized: ").Append(Normalized).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetEthMarketplaceDataRequest);
        }

        /// <summary>
        /// Returns true if GetEthMarketplaceDataRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of GetEthMarketplaceDataRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetEthMarketplaceDataRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CollectionAddress == input.CollectionAddress ||
                    this.CollectionAddress != null &&
                    input.CollectionAddress != null &&
                    this.CollectionAddress.SequenceEqual(input.CollectionAddress)
                ) && 
                (
                    this.SubCollectionTags == input.SubCollectionTags ||
                    this.SubCollectionTags != null &&
                    input.SubCollectionTags != null &&
                    this.SubCollectionTags.SequenceEqual(input.SubCollectionTags)
                ) && 
                (
                    this.Normalized == input.Normalized ||
                    this.Normalized.Equals(input.Normalized)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CollectionAddress != null)
                {
                    hashCode = (hashCode * 59) + this.CollectionAddress.GetHashCode();
                }
                if (this.SubCollectionTags != null)
                {
                    hashCode = (hashCode * 59) + this.SubCollectionTags.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Normalized.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
