/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GetPolDefaultCollectionRiskRequest
    /// </summary>
    [DataContract(Name = "getPolDefaultCollectionRisk_request")]
    public partial class GetPolDefaultCollectionRiskRequest : IEquatable<GetPolDefaultCollectionRiskRequest>, IValidatableObject
    {
        /// <summary>
        /// The currency to report results in
        /// </summary>
        /// <value>The currency to report results in</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ReptCurrEnum
        {
            /// <summary>
            /// Enum Eth for value: eth
            /// </summary>
            [EnumMember(Value = "eth")]
            Eth = 1,

            /// <summary>
            /// Enum Usd for value: usd
            /// </summary>
            [EnumMember(Value = "usd")]
            Usd = 2,

            /// <summary>
            /// Enum Matic for value: matic
            /// </summary>
            [EnumMember(Value = "matic")]
            Matic = 3

        }


        /// <summary>
        /// The currency to report results in
        /// </summary>
        /// <value>The currency to report results in</value>
        /// <example>&quot;eth&quot;</example>
        [DataMember(Name = "rept_curr", EmitDefaultValue = false)]
        public ReptCurrEnum? ReptCurr { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetPolDefaultCollectionRiskRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetPolDefaultCollectionRiskRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetPolDefaultCollectionRiskRequest" /> class.
        /// </summary>
        /// <param name="collectionAddress">The contract address of the token collection. (required).</param>
        /// <param name="holdingPeriod">The holding period to evaluate risk for, e.g. &#39;12M&#39; (required).</param>
        /// <param name="reptCurr">The currency to report results in.</param>
        /// <param name="amount">The amount of tokens in your portfolio.</param>
        /// <param name="drawdown">If true, report drawdown volatility (based on negative returns only)..</param>
        public GetPolDefaultCollectionRiskRequest(string collectionAddress = default(string), string holdingPeriod = default(string), ReptCurrEnum? reptCurr = default(ReptCurrEnum?), int amount = default(int), bool drawdown = default(bool))
        {
            // to ensure "collectionAddress" is required (not null)
            if (collectionAddress == null)
            {
                throw new ArgumentNullException("collectionAddress is a required property for GetPolDefaultCollectionRiskRequest and cannot be null");
            }
            this.CollectionAddress = collectionAddress;
            // to ensure "holdingPeriod" is required (not null)
            if (holdingPeriod == null)
            {
                throw new ArgumentNullException("holdingPeriod is a required property for GetPolDefaultCollectionRiskRequest and cannot be null");
            }
            this.HoldingPeriod = holdingPeriod;
            this.ReptCurr = reptCurr;
            this.Amount = amount;
            this.Drawdown = drawdown;
        }

        /// <summary>
        /// The contract address of the token collection.
        /// </summary>
        /// <value>The contract address of the token collection.</value>
        /// <example>&quot;0xfbe3ab0cbfbd17d06bdd73aa3f55aaf038720f59&quot;</example>
        [DataMember(Name = "collection_address", IsRequired = true, EmitDefaultValue = true)]
        public string CollectionAddress { get; set; }

        /// <summary>
        /// The holding period to evaluate risk for, e.g. &#39;12M&#39;
        /// </summary>
        /// <value>The holding period to evaluate risk for, e.g. &#39;12M&#39;</value>
        /// <example>&quot;6M&quot;</example>
        [DataMember(Name = "holding_period", IsRequired = true, EmitDefaultValue = true)]
        public string HoldingPeriod { get; set; }

        /// <summary>
        /// The amount of tokens in your portfolio
        /// </summary>
        /// <value>The amount of tokens in your portfolio</value>
        /// <example>1</example>
        [DataMember(Name = "amount", EmitDefaultValue = false)]
        public int Amount { get; set; }

        /// <summary>
        /// If true, report drawdown volatility (based on negative returns only).
        /// </summary>
        /// <value>If true, report drawdown volatility (based on negative returns only).</value>
        /// <example>false</example>
        [DataMember(Name = "drawdown", EmitDefaultValue = true)]
        public bool Drawdown { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetPolDefaultCollectionRiskRequest {\n");
            sb.Append("  CollectionAddress: ").Append(CollectionAddress).Append("\n");
            sb.Append("  HoldingPeriod: ").Append(HoldingPeriod).Append("\n");
            sb.Append("  ReptCurr: ").Append(ReptCurr).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Drawdown: ").Append(Drawdown).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetPolDefaultCollectionRiskRequest);
        }

        /// <summary>
        /// Returns true if GetPolDefaultCollectionRiskRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of GetPolDefaultCollectionRiskRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetPolDefaultCollectionRiskRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CollectionAddress == input.CollectionAddress ||
                    (this.CollectionAddress != null &&
                    this.CollectionAddress.Equals(input.CollectionAddress))
                ) && 
                (
                    this.HoldingPeriod == input.HoldingPeriod ||
                    (this.HoldingPeriod != null &&
                    this.HoldingPeriod.Equals(input.HoldingPeriod))
                ) && 
                (
                    this.ReptCurr == input.ReptCurr ||
                    this.ReptCurr.Equals(input.ReptCurr)
                ) && 
                (
                    this.Amount == input.Amount ||
                    this.Amount.Equals(input.Amount)
                ) && 
                (
                    this.Drawdown == input.Drawdown ||
                    this.Drawdown.Equals(input.Drawdown)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CollectionAddress != null)
                {
                    hashCode = (hashCode * 59) + this.CollectionAddress.GetHashCode();
                }
                if (this.HoldingPeriod != null)
                {
                    hashCode = (hashCode * 59) + this.HoldingPeriod.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ReptCurr.GetHashCode();
                hashCode = (hashCode * 59) + this.Amount.GetHashCode();
                hashCode = (hashCode * 59) + this.Drawdown.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
