/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GetPolMarketplaceDataRequest
    /// </summary>
    [DataContract(Name = "getPolMarketplaceData_request")]
    public partial class GetPolMarketplaceDataRequest : IEquatable<GetPolMarketplaceDataRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetPolMarketplaceDataRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetPolMarketplaceDataRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetPolMarketplaceDataRequest" /> class.
        /// </summary>
        /// <param name="collectionAddress">Array of collection addresses (required).</param>
        public GetPolMarketplaceDataRequest(List<string> collectionAddress = default(List<string>))
        {
            // to ensure "collectionAddress" is required (not null)
            if (collectionAddress == null)
            {
                throw new ArgumentNullException("collectionAddress is a required property for GetPolMarketplaceDataRequest and cannot be null");
            }
            this.CollectionAddress = collectionAddress;
        }

        /// <summary>
        /// Array of collection addresses
        /// </summary>
        /// <value>Array of collection addresses</value>
        [DataMember(Name = "collection_address", IsRequired = true, EmitDefaultValue = true)]
        public List<string> CollectionAddress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetPolMarketplaceDataRequest {\n");
            sb.Append("  CollectionAddress: ").Append(CollectionAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetPolMarketplaceDataRequest);
        }

        /// <summary>
        /// Returns true if GetPolMarketplaceDataRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of GetPolMarketplaceDataRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetPolMarketplaceDataRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CollectionAddress == input.CollectionAddress ||
                    this.CollectionAddress != null &&
                    input.CollectionAddress != null &&
                    this.CollectionAddress.SequenceEqual(input.CollectionAddress)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CollectionAddress != null)
                {
                    hashCode = (hashCode * 59) + this.CollectionAddress.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
