/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GetSolRarityRequest
    /// </summary>
    [DataContract(Name = "getSolRarity_request")]
    public partial class GetSolRarityRequest : IEquatable<GetSolRarityRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSolRarityRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetSolRarityRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSolRarityRequest" /> class.
        /// </summary>
        /// <param name="collectionTag">The Gallop tag for the Solana collection. Please see sol/getCollections endpoint. (required).</param>
        /// <param name="mintAddress">A list of token addresses..</param>
        /// <param name="weights">Dict containing trait keys and weight values..</param>
        public GetSolRarityRequest(string collectionTag = default(string), List<string> mintAddress = default(List<string>), Object weights = default(Object))
        {
            // to ensure "collectionTag" is required (not null)
            if (collectionTag == null)
            {
                throw new ArgumentNullException("collectionTag is a required property for GetSolRarityRequest and cannot be null");
            }
            this.CollectionTag = collectionTag;
            this.MintAddress = mintAddress;
            this.Weights = weights;
        }

        /// <summary>
        /// The Gallop tag for the Solana collection. Please see sol/getCollections endpoint.
        /// </summary>
        /// <value>The Gallop tag for the Solana collection. Please see sol/getCollections endpoint.</value>
        [DataMember(Name = "collection_tag", IsRequired = true, EmitDefaultValue = true)]
        public string CollectionTag { get; set; }

        /// <summary>
        /// A list of token addresses.
        /// </summary>
        /// <value>A list of token addresses.</value>
        [DataMember(Name = "mint_address", EmitDefaultValue = false)]
        public List<string> MintAddress { get; set; }

        /// <summary>
        /// Dict containing trait keys and weight values.
        /// </summary>
        /// <value>Dict containing trait keys and weight values.</value>
        [DataMember(Name = "weights", EmitDefaultValue = false)]
        public Object Weights { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetSolRarityRequest {\n");
            sb.Append("  CollectionTag: ").Append(CollectionTag).Append("\n");
            sb.Append("  MintAddress: ").Append(MintAddress).Append("\n");
            sb.Append("  Weights: ").Append(Weights).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetSolRarityRequest);
        }

        /// <summary>
        /// Returns true if GetSolRarityRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of GetSolRarityRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetSolRarityRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CollectionTag == input.CollectionTag ||
                    (this.CollectionTag != null &&
                    this.CollectionTag.Equals(input.CollectionTag))
                ) && 
                (
                    this.MintAddress == input.MintAddress ||
                    this.MintAddress != null &&
                    input.MintAddress != null &&
                    this.MintAddress.SequenceEqual(input.MintAddress)
                ) && 
                (
                    this.Weights == input.Weights ||
                    (this.Weights != null &&
                    this.Weights.Equals(input.Weights))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CollectionTag != null)
                {
                    hashCode = (hashCode * 59) + this.CollectionTag.GetHashCode();
                }
                if (this.MintAddress != null)
                {
                    hashCode = (hashCode * 59) + this.MintAddress.GetHashCode();
                }
                if (this.Weights != null)
                {
                    hashCode = (hashCode * 59) + this.Weights.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
