/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GetSolAccountNFTsRequest
    /// </summary>
    [DataContract(Name = "getSolAccountNFTs_request")]
    public partial class GetSolAccountNFTsRequest : IEquatable<GetSolAccountNFTsRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSolAccountNFTsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetSolAccountNFTsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSolAccountNFTsRequest" /> class.
        /// </summary>
        /// <param name="accountAddress">The account address to query. (required).</param>
        public GetSolAccountNFTsRequest(string accountAddress = default(string))
        {
            // to ensure "accountAddress" is required (not null)
            if (accountAddress == null)
            {
                throw new ArgumentNullException("accountAddress is a required property for GetSolAccountNFTsRequest and cannot be null");
            }
            this.AccountAddress = accountAddress;
        }

        /// <summary>
        /// The account address to query.
        /// </summary>
        /// <value>The account address to query.</value>
        [DataMember(Name = "account_address", IsRequired = true, EmitDefaultValue = true)]
        public string AccountAddress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetSolAccountNFTsRequest {\n");
            sb.Append("  AccountAddress: ").Append(AccountAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetSolAccountNFTsRequest);
        }

        /// <summary>
        /// Returns true if GetSolAccountNFTsRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of GetSolAccountNFTsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetSolAccountNFTsRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AccountAddress == input.AccountAddress ||
                    (this.AccountAddress != null &&
                    this.AccountAddress.Equals(input.AccountAddress))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AccountAddress != null)
                {
                    hashCode = (hashCode * 59) + this.AccountAddress.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
