/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GetSolWashTradeRequest
    /// </summary>
    [DataContract(Name = "getSolWashTrade_request")]
    public partial class GetSolWashTradeRequest : IEquatable<GetSolWashTradeRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSolWashTradeRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetSolWashTradeRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSolWashTradeRequest" /> class.
        /// </summary>
        /// <param name="firstSignature">The first signature to valildate. (required).</param>
        public GetSolWashTradeRequest(string firstSignature = default(string))
        {
            // to ensure "firstSignature" is required (not null)
            if (firstSignature == null)
            {
                throw new ArgumentNullException("firstSignature is a required property for GetSolWashTradeRequest and cannot be null");
            }
            this.FirstSignature = firstSignature;
        }

        /// <summary>
        /// The first signature to valildate.
        /// </summary>
        /// <value>The first signature to valildate.</value>
        [DataMember(Name = "first_signature", IsRequired = true, EmitDefaultValue = true)]
        public string FirstSignature { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetSolWashTradeRequest {\n");
            sb.Append("  FirstSignature: ").Append(FirstSignature).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetSolWashTradeRequest);
        }

        /// <summary>
        /// Returns true if GetSolWashTradeRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of GetSolWashTradeRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetSolWashTradeRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.FirstSignature == input.FirstSignature ||
                    (this.FirstSignature != null &&
                    this.FirstSignature.Equals(input.FirstSignature))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FirstSignature != null)
                {
                    hashCode = (hashCode * 59) + this.FirstSignature.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
