/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing PolygonApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PolygonApiTests : IDisposable
    {
        private PolygonApi instance;

        public PolygonApiTests()
        {
            instance = new PolygonApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PolygonApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PolygonApi
            //Assert.IsType<PolygonApi>(instance);
        }

        /// <summary>
        /// Test GetPolCollectionForecasts
        /// </summary>
        [Fact]
        public void GetPolCollectionForecastsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolCollectionForecastsRequest getPolCollectionForecastsRequest = null;
            //instance.GetPolCollectionForecasts(getPolCollectionForecastsRequest);
        }

        /// <summary>
        /// Test GetPolCollectionOwners
        /// </summary>
        [Fact]
        public void GetPolCollectionOwnersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolCollectionOwnersRequest getPolCollectionOwnersRequest = null;
            //instance.GetPolCollectionOwners(getPolCollectionOwnersRequest);
        }

        /// <summary>
        /// Test GetPolCollectionPriceDiff
        /// </summary>
        [Fact]
        public void GetPolCollectionPriceDiffTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolCollectionPriceDiffRequest getPolCollectionPriceDiffRequest = null;
            //instance.GetPolCollectionPriceDiff(getPolCollectionPriceDiffRequest);
        }

        /// <summary>
        /// Test GetPolCollectionSalesOHLC
        /// </summary>
        [Fact]
        public void GetPolCollectionSalesOHLCTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolCollectionSalesOHLCRequest getPolCollectionSalesOHLCRequest = null;
            //instance.GetPolCollectionSalesOHLC(getPolCollectionSalesOHLCRequest);
        }

        /// <summary>
        /// Test GetPolCollectionSummary
        /// </summary>
        [Fact]
        public void GetPolCollectionSummaryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolCollectionSummaryRequest getPolCollectionSummaryRequest = null;
            //instance.GetPolCollectionSummary(getPolCollectionSummaryRequest);
        }

        /// <summary>
        /// Test GetPolCollectionTraits
        /// </summary>
        [Fact]
        public void GetPolCollectionTraitsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolCollectionTraitsRequest getPolCollectionTraitsRequest = null;
            //instance.GetPolCollectionTraits(getPolCollectionTraitsRequest);
        }

        /// <summary>
        /// Test GetPolCollectionTransactions
        /// </summary>
        [Fact]
        public void GetPolCollectionTransactionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolCollectionTransactionsRequest getPolCollectionTransactionsRequest = null;
            //instance.GetPolCollectionTransactions(getPolCollectionTransactionsRequest);
        }

        /// <summary>
        /// Test GetPolCollections
        /// </summary>
        [Fact]
        public void GetPolCollectionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolCollectionsRequest getPolCollectionsRequest = null;
            //instance.GetPolCollections(getPolCollectionsRequest);
        }

        /// <summary>
        /// Test GetPolCustomCollectionRisk
        /// </summary>
        [Fact]
        public void GetPolCustomCollectionRiskTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolCustomCollectionRiskRequest getPolCustomCollectionRiskRequest = null;
            //instance.GetPolCustomCollectionRisk(getPolCustomCollectionRiskRequest);
        }

        /// <summary>
        /// Test GetPolCustomTokenRisk
        /// </summary>
        [Fact]
        public void GetPolCustomTokenRiskTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolCustomTokenRiskRequest getPolCustomTokenRiskRequest = null;
            //instance.GetPolCustomTokenRisk(getPolCustomTokenRiskRequest);
        }

        /// <summary>
        /// Test GetPolDefaultCollectionRisk
        /// </summary>
        [Fact]
        public void GetPolDefaultCollectionRiskTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolDefaultCollectionRiskRequest getPolDefaultCollectionRiskRequest = null;
            //instance.GetPolDefaultCollectionRisk(getPolDefaultCollectionRiskRequest);
        }

        /// <summary>
        /// Test GetPolDefaultTokenRisk
        /// </summary>
        [Fact]
        public void GetPolDefaultTokenRiskTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolDefaultTokenRiskRequest getPolDefaultTokenRiskRequest = null;
            //instance.GetPolDefaultTokenRisk(getPolDefaultTokenRiskRequest);
        }

        /// <summary>
        /// Test GetPolHistoricalTransactions
        /// </summary>
        [Fact]
        public void GetPolHistoricalTransactionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolHistoricalTransactionsRequest getPolHistoricalTransactionsRequest = null;
            //instance.GetPolHistoricalTransactions(getPolHistoricalTransactionsRequest);
        }

        /// <summary>
        /// Test GetPolLeaderBoard
        /// </summary>
        [Fact]
        public void GetPolLeaderBoardTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetEthLeaderBoardRequest getEthLeaderBoardRequest = null;
            //instance.GetPolLeaderBoard(getEthLeaderBoardRequest);
        }

        /// <summary>
        /// Test GetPolMarketplaceData
        /// </summary>
        [Fact]
        public void GetPolMarketplaceDataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolMarketplaceDataRequest getPolMarketplaceDataRequest = null;
            //instance.GetPolMarketplaceData(getPolMarketplaceDataRequest);
        }

        /// <summary>
        /// Test GetPolMarketplaceFloorPrice
        /// </summary>
        [Fact]
        public void GetPolMarketplaceFloorPriceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolMarketplaceFloorPriceRequest getPolMarketplaceFloorPriceRequest = null;
            //instance.GetPolMarketplaceFloorPrice(getPolMarketplaceFloorPriceRequest);
        }

        /// <summary>
        /// Test GetPolRarity
        /// </summary>
        [Fact]
        public void GetPolRarityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolRarityRequest getPolRarityRequest = null;
            //instance.GetPolRarity(getPolRarityRequest);
        }

        /// <summary>
        /// Test GetPolTokenAppraisal
        /// </summary>
        [Fact]
        public void GetPolTokenAppraisalTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolTokenAppraisalRequest getPolTokenAppraisalRequest = null;
            //instance.GetPolTokenAppraisal(getPolTokenAppraisalRequest);
        }

        /// <summary>
        /// Test GetPolTokenForecasts
        /// </summary>
        [Fact]
        public void GetPolTokenForecastsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolTokenForecastsRequest getPolTokenForecastsRequest = null;
            //instance.GetPolTokenForecasts(getPolTokenForecastsRequest);
        }

        /// <summary>
        /// Test GetPolTokenSummary
        /// </summary>
        [Fact]
        public void GetPolTokenSummaryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolTokenSummaryRequest getPolTokenSummaryRequest = null;
            //instance.GetPolTokenSummary(getPolTokenSummaryRequest);
        }

        /// <summary>
        /// Test GetPolTokenTransactions
        /// </summary>
        [Fact]
        public void GetPolTokenTransactionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolTokenTransactionsRequest getPolTokenTransactionsRequest = null;
            //instance.GetPolTokenTransactions(getPolTokenTransactionsRequest);
        }

        /// <summary>
        /// Test GetPolTokens
        /// </summary>
        [Fact]
        public void GetPolTokensTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolTokensRequest getPolTokensRequest = null;
            //instance.GetPolTokens(getPolTokensRequest);
        }

        /// <summary>
        /// Test GetPolWalletLabels
        /// </summary>
        [Fact]
        public void GetPolWalletLabelsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetEthWalletLabelsRequest getEthWalletLabelsRequest = null;
            //instance.GetPolWalletLabels(getEthWalletLabelsRequest);
        }

        /// <summary>
        /// Test GetPolWalletNFTs
        /// </summary>
        [Fact]
        public void GetPolWalletNFTsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolWalletNFTsRequest getPolWalletNFTsRequest = null;
            //instance.GetPolWalletNFTs(getPolWalletNFTsRequest);
        }

        /// <summary>
        /// Test GetPolWalletTransactions
        /// </summary>
        [Fact]
        public void GetPolWalletTransactionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolWalletTransactionsRequest getPolWalletTransactionsRequest = null;
            //instance.GetPolWalletTransactions(getPolWalletTransactionsRequest);
        }

        /// <summary>
        /// Test GetPolWashTrade
        /// </summary>
        [Fact]
        public void GetPolWashTradeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolWashTradeRequest getPolWashTradeRequest = null;
            //instance.GetPolWashTrade(getPolWashTradeRequest);
        }

        /// <summary>
        /// Test GetPolWashTransactions
        /// </summary>
        [Fact]
        public void GetPolWashTransactionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPolWashTransactionsRequest getPolWashTransactionsRequest = null;
            //instance.GetPolWashTransactions(getPolWashTransactionsRequest);
        }
    }
}
