/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetEthWalletTransactionsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetEthWalletTransactionsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetEthWalletTransactionsRequest
        //private GetEthWalletTransactionsRequest instance;

        public GetEthWalletTransactionsRequestTests()
        {
            // TODO uncomment below to create an instance of GetEthWalletTransactionsRequest
            //instance = new GetEthWalletTransactionsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetEthWalletTransactionsRequest
        /// </summary>
        [Fact]
        public void GetEthWalletTransactionsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetEthWalletTransactionsRequest
            //Assert.IsType<GetEthWalletTransactionsRequest>(instance);
        }


        /// <summary>
        /// Test the property 'WalletAddress'
        /// </summary>
        [Fact]
        public void WalletAddressTest()
        {
            // TODO unit test for the property 'WalletAddress'
        }
        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

    }

}
