/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetEthCollectionFloorPriceOHLCRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetEthCollectionFloorPriceOHLCRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetEthCollectionFloorPriceOHLCRequest
        //private GetEthCollectionFloorPriceOHLCRequest instance;

        public GetEthCollectionFloorPriceOHLCRequestTests()
        {
            // TODO uncomment below to create an instance of GetEthCollectionFloorPriceOHLCRequest
            //instance = new GetEthCollectionFloorPriceOHLCRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetEthCollectionFloorPriceOHLCRequest
        /// </summary>
        [Fact]
        public void GetEthCollectionFloorPriceOHLCRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetEthCollectionFloorPriceOHLCRequest
            //Assert.IsType<GetEthCollectionFloorPriceOHLCRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CollectionAddress'
        /// </summary>
        [Fact]
        public void CollectionAddressTest()
        {
            // TODO unit test for the property 'CollectionAddress'
        }
        /// <summary>
        /// Test the property 'Frequency'
        /// </summary>
        [Fact]
        public void FrequencyTest()
        {
            // TODO unit test for the property 'Frequency'
        }
        /// <summary>
        /// Test the property 'GroupBy'
        /// </summary>
        [Fact]
        public void GroupByTest()
        {
            // TODO unit test for the property 'GroupBy'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }

    }

}
