/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetEthLeaderBoardRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetEthLeaderBoardRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetEthLeaderBoardRequest
        //private GetEthLeaderBoardRequest instance;

        public GetEthLeaderBoardRequestTests()
        {
            // TODO uncomment below to create an instance of GetEthLeaderBoardRequest
            //instance = new GetEthLeaderBoardRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetEthLeaderBoardRequest
        /// </summary>
        [Fact]
        public void GetEthLeaderBoardRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetEthLeaderBoardRequest
            //Assert.IsType<GetEthLeaderBoardRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'Interval'
        /// </summary>
        [Fact]
        public void IntervalTest()
        {
            // TODO unit test for the property 'Interval'
        }
        /// <summary>
        /// Test the property 'RankingMetric'
        /// </summary>
        [Fact]
        public void RankingMetricTest()
        {
            // TODO unit test for the property 'RankingMetric'
        }

    }

}
