/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetEthTokenSummaryRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetEthTokenSummaryRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetEthTokenSummaryRequest
        //private GetEthTokenSummaryRequest instance;

        public GetEthTokenSummaryRequestTests()
        {
            // TODO uncomment below to create an instance of GetEthTokenSummaryRequest
            //instance = new GetEthTokenSummaryRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetEthTokenSummaryRequest
        /// </summary>
        [Fact]
        public void GetEthTokenSummaryRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetEthTokenSummaryRequest
            //Assert.IsType<GetEthTokenSummaryRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CollectionAddress'
        /// </summary>
        [Fact]
        public void CollectionAddressTest()
        {
            // TODO unit test for the property 'CollectionAddress'
        }
        /// <summary>
        /// Test the property 'TokenId'
        /// </summary>
        [Fact]
        public void TokenIdTest()
        {
            // TODO unit test for the property 'TokenId'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'ReptCurr'
        /// </summary>
        [Fact]
        public void ReptCurrTest()
        {
            // TODO unit test for the property 'ReptCurr'
        }
        /// <summary>
        /// Test the property 'ExcludeWash'
        /// </summary>
        [Fact]
        public void ExcludeWashTest()
        {
            // TODO unit test for the property 'ExcludeWash'
        }

    }

}
