/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetEthCustomCollectionRiskRequestArcParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetEthCustomCollectionRiskRequestArcParamsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetEthCustomCollectionRiskRequestArcParams
        //private GetEthCustomCollectionRiskRequestArcParams instance;

        public GetEthCustomCollectionRiskRequestArcParamsTests()
        {
            // TODO uncomment below to create an instance of GetEthCustomCollectionRiskRequestArcParams
            //instance = new GetEthCustomCollectionRiskRequestArcParams();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetEthCustomCollectionRiskRequestArcParams
        /// </summary>
        [Fact]
        public void GetEthCustomCollectionRiskRequestArcParamsInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetEthCustomCollectionRiskRequestArcParams
            //Assert.IsType<GetEthCustomCollectionRiskRequestArcParams>(instance);
        }


        /// <summary>
        /// Test the property 'Mean'
        /// </summary>
        [Fact]
        public void MeanTest()
        {
            // TODO unit test for the property 'Mean'
        }
        /// <summary>
        /// Test the property 'Lags'
        /// </summary>
        [Fact]
        public void LagsTest()
        {
            // TODO unit test for the property 'Lags'
        }
        /// <summary>
        /// Test the property 'Vol'
        /// </summary>
        [Fact]
        public void VolTest()
        {
            // TODO unit test for the property 'Vol'
        }
        /// <summary>
        /// Test the property 'P'
        /// </summary>
        [Fact]
        public void PTest()
        {
            // TODO unit test for the property 'P'
        }
        /// <summary>
        /// Test the property 'Dist'
        /// </summary>
        [Fact]
        public void DistTest()
        {
            // TODO unit test for the property 'Dist'
        }

    }

}
