/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetEthHistoricalEventsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetEthHistoricalEventsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetEthHistoricalEventsRequest
        //private GetEthHistoricalEventsRequest instance;

        public GetEthHistoricalEventsRequestTests()
        {
            // TODO uncomment below to create an instance of GetEthHistoricalEventsRequest
            //instance = new GetEthHistoricalEventsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetEthHistoricalEventsRequest
        /// </summary>
        [Fact]
        public void GetEthHistoricalEventsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetEthHistoricalEventsRequest
            //Assert.IsType<GetEthHistoricalEventsRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CollectionAddress'
        /// </summary>
        [Fact]
        public void CollectionAddressTest()
        {
            // TODO unit test for the property 'CollectionAddress'
        }
        /// <summary>
        /// Test the property 'TokenId'
        /// </summary>
        [Fact]
        public void TokenIdTest()
        {
            // TODO unit test for the property 'TokenId'
        }
        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }

    }

}
