/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetEthWashTradeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetEthWashTradeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetEthWashTradeRequest
        //private GetEthWashTradeRequest instance;

        public GetEthWashTradeRequestTests()
        {
            // TODO uncomment below to create an instance of GetEthWashTradeRequest
            //instance = new GetEthWashTradeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetEthWashTradeRequest
        /// </summary>
        [Fact]
        public void GetEthWashTradeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetEthWashTradeRequest
            //Assert.IsType<GetEthWashTradeRequest>(instance);
        }


        /// <summary>
        /// Test the property 'TransactionHash'
        /// </summary>
        [Fact]
        public void TransactionHashTest()
        {
            // TODO unit test for the property 'TransactionHash'
        }

    }

}
