/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetPolTokenAppraisalRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetPolTokenAppraisalRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetPolTokenAppraisalRequest
        //private GetPolTokenAppraisalRequest instance;

        public GetPolTokenAppraisalRequestTests()
        {
            // TODO uncomment below to create an instance of GetPolTokenAppraisalRequest
            //instance = new GetPolTokenAppraisalRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetPolTokenAppraisalRequest
        /// </summary>
        [Fact]
        public void GetPolTokenAppraisalRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetPolTokenAppraisalRequest
            //Assert.IsType<GetPolTokenAppraisalRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CollectionAddress'
        /// </summary>
        [Fact]
        public void CollectionAddressTest()
        {
            // TODO unit test for the property 'CollectionAddress'
        }
        /// <summary>
        /// Test the property 'TokenId'
        /// </summary>
        [Fact]
        public void TokenIdTest()
        {
            // TODO unit test for the property 'TokenId'
        }
        /// <summary>
        /// Test the property 'ReptCurr'
        /// </summary>
        [Fact]
        public void ReptCurrTest()
        {
            // TODO unit test for the property 'ReptCurr'
        }
        /// <summary>
        /// Test the property 'Frequency'
        /// </summary>
        [Fact]
        public void FrequencyTest()
        {
            // TODO unit test for the property 'Frequency'
        }
        /// <summary>
        /// Test the property 'Horizon'
        /// </summary>
        [Fact]
        public void HorizonTest()
        {
            // TODO unit test for the property 'Horizon'
        }
        /// <summary>
        /// Test the property 'Alpha'
        /// </summary>
        [Fact]
        public void AlphaTest()
        {
            // TODO unit test for the property 'Alpha'
        }
        /// <summary>
        /// Test the property 'ExcludeWash'
        /// </summary>
        [Fact]
        public void ExcludeWashTest()
        {
            // TODO unit test for the property 'ExcludeWash'
        }

    }

}
