/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetPolCollectionsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetPolCollectionsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetPolCollectionsRequest
        //private GetPolCollectionsRequest instance;

        public GetPolCollectionsRequestTests()
        {
            // TODO uncomment below to create an instance of GetPolCollectionsRequest
            //instance = new GetPolCollectionsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetPolCollectionsRequest
        /// </summary>
        [Fact]
        public void GetPolCollectionsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetPolCollectionsRequest
            //Assert.IsType<GetPolCollectionsRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'CollectionName'
        /// </summary>
        [Fact]
        public void CollectionNameTest()
        {
            // TODO unit test for the property 'CollectionName'
        }
        /// <summary>
        /// Test the property 'Traded'
        /// </summary>
        [Fact]
        public void TradedTest()
        {
            // TODO unit test for the property 'Traded'
        }
        /// <summary>
        /// Test the property 'CreatedAfter'
        /// </summary>
        [Fact]
        public void CreatedAfterTest()
        {
            // TODO unit test for the property 'CreatedAfter'
        }
        /// <summary>
        /// Test the property 'SortBy'
        /// </summary>
        [Fact]
        public void SortByTest()
        {
            // TODO unit test for the property 'SortBy'
        }

    }

}
