/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetPolCollectionForecastsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetPolCollectionForecastsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetPolCollectionForecastsRequest
        //private GetPolCollectionForecastsRequest instance;

        public GetPolCollectionForecastsRequestTests()
        {
            // TODO uncomment below to create an instance of GetPolCollectionForecastsRequest
            //instance = new GetPolCollectionForecastsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetPolCollectionForecastsRequest
        /// </summary>
        [Fact]
        public void GetPolCollectionForecastsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetPolCollectionForecastsRequest
            //Assert.IsType<GetPolCollectionForecastsRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CollectionAddress'
        /// </summary>
        [Fact]
        public void CollectionAddressTest()
        {
            // TODO unit test for the property 'CollectionAddress'
        }
        /// <summary>
        /// Test the property 'Percentiles'
        /// </summary>
        [Fact]
        public void PercentilesTest()
        {
            // TODO unit test for the property 'Percentiles'
        }
        /// <summary>
        /// Test the property 'Voltype'
        /// </summary>
        [Fact]
        public void VoltypeTest()
        {
            // TODO unit test for the property 'Voltype'
        }
        /// <summary>
        /// Test the property 'Horizon'
        /// </summary>
        [Fact]
        public void HorizonTest()
        {
            // TODO unit test for the property 'Horizon'
        }
        /// <summary>
        /// Test the property 'Frequency'
        /// </summary>
        [Fact]
        public void FrequencyTest()
        {
            // TODO unit test for the property 'Frequency'
        }
        /// <summary>
        /// Test the property 'Dist'
        /// </summary>
        [Fact]
        public void DistTest()
        {
            // TODO unit test for the property 'Dist'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'ReturnPriceForecasts'
        /// </summary>
        [Fact]
        public void ReturnPriceForecastsTest()
        {
            // TODO unit test for the property 'ReturnPriceForecasts'
        }
        /// <summary>
        /// Test the property 'Alpha'
        /// </summary>
        [Fact]
        public void AlphaTest()
        {
            // TODO unit test for the property 'Alpha'
        }
        /// <summary>
        /// Test the property 'ReptCurr'
        /// </summary>
        [Fact]
        public void ReptCurrTest()
        {
            // TODO unit test for the property 'ReptCurr'
        }
        /// <summary>
        /// Test the property 'ExcludeWash'
        /// </summary>
        [Fact]
        public void ExcludeWashTest()
        {
            // TODO unit test for the property 'ExcludeWash'
        }
        /// <summary>
        /// Test the property 'ArchParams'
        /// </summary>
        [Fact]
        public void ArchParamsTest()
        {
            // TODO unit test for the property 'ArchParams'
        }

    }

}
