/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetPolCollectionTransactionsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetPolCollectionTransactionsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetPolCollectionTransactionsRequest
        //private GetPolCollectionTransactionsRequest instance;

        public GetPolCollectionTransactionsRequestTests()
        {
            // TODO uncomment below to create an instance of GetPolCollectionTransactionsRequest
            //instance = new GetPolCollectionTransactionsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetPolCollectionTransactionsRequest
        /// </summary>
        [Fact]
        public void GetPolCollectionTransactionsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetPolCollectionTransactionsRequest
            //Assert.IsType<GetPolCollectionTransactionsRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CollectionAddress'
        /// </summary>
        [Fact]
        public void CollectionAddressTest()
        {
            // TODO unit test for the property 'CollectionAddress'
        }
        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'StartBlockNumber'
        /// </summary>
        [Fact]
        public void StartBlockNumberTest()
        {
            // TODO unit test for the property 'StartBlockNumber'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }

    }

}
