/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetSolMarketplaceFloorPriceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSolMarketplaceFloorPriceRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSolMarketplaceFloorPriceRequest
        //private GetSolMarketplaceFloorPriceRequest instance;

        public GetSolMarketplaceFloorPriceRequestTests()
        {
            // TODO uncomment below to create an instance of GetSolMarketplaceFloorPriceRequest
            //instance = new GetSolMarketplaceFloorPriceRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSolMarketplaceFloorPriceRequest
        /// </summary>
        [Fact]
        public void GetSolMarketplaceFloorPriceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSolMarketplaceFloorPriceRequest
            //Assert.IsType<GetSolMarketplaceFloorPriceRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'CollectionTag'
        /// </summary>
        [Fact]
        public void CollectionTagTest()
        {
            // TODO unit test for the property 'CollectionTag'
        }

    }

}
