/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetSolCollectionSummaryRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSolCollectionSummaryRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSolCollectionSummaryRequest
        //private GetSolCollectionSummaryRequest instance;

        public GetSolCollectionSummaryRequestTests()
        {
            // TODO uncomment below to create an instance of GetSolCollectionSummaryRequest
            //instance = new GetSolCollectionSummaryRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSolCollectionSummaryRequest
        /// </summary>
        [Fact]
        public void GetSolCollectionSummaryRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSolCollectionSummaryRequest
            //Assert.IsType<GetSolCollectionSummaryRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CollectionTag'
        /// </summary>
        [Fact]
        public void CollectionTagTest()
        {
            // TODO unit test for the property 'CollectionTag'
        }
        /// <summary>
        /// Test the property 'GroupBy'
        /// </summary>
        [Fact]
        public void GroupByTest()
        {
            // TODO unit test for the property 'GroupBy'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'ReptCurr'
        /// </summary>
        [Fact]
        public void ReptCurrTest()
        {
            // TODO unit test for the property 'ReptCurr'
        }
        /// <summary>
        /// Test the property 'ExcludeWash'
        /// </summary>
        [Fact]
        public void ExcludeWashTest()
        {
            // TODO unit test for the property 'ExcludeWash'
        }

    }

}
