/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetSolDefaultCollectionRiskRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSolDefaultCollectionRiskRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSolDefaultCollectionRiskRequest
        //private GetSolDefaultCollectionRiskRequest instance;

        public GetSolDefaultCollectionRiskRequestTests()
        {
            // TODO uncomment below to create an instance of GetSolDefaultCollectionRiskRequest
            //instance = new GetSolDefaultCollectionRiskRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSolDefaultCollectionRiskRequest
        /// </summary>
        [Fact]
        public void GetSolDefaultCollectionRiskRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSolDefaultCollectionRiskRequest
            //Assert.IsType<GetSolDefaultCollectionRiskRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CollectionTag'
        /// </summary>
        [Fact]
        public void CollectionTagTest()
        {
            // TODO unit test for the property 'CollectionTag'
        }
        /// <summary>
        /// Test the property 'HoldingPeriod'
        /// </summary>
        [Fact]
        public void HoldingPeriodTest()
        {
            // TODO unit test for the property 'HoldingPeriod'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'ReptCurr'
        /// </summary>
        [Fact]
        public void ReptCurrTest()
        {
            // TODO unit test for the property 'ReptCurr'
        }
        /// <summary>
        /// Test the property 'Drawdown'
        /// </summary>
        [Fact]
        public void DrawdownTest()
        {
            // TODO unit test for the property 'Drawdown'
        }

    }

}
