/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetSolWashTradeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSolWashTradeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSolWashTradeRequest
        //private GetSolWashTradeRequest instance;

        public GetSolWashTradeRequestTests()
        {
            // TODO uncomment below to create an instance of GetSolWashTradeRequest
            //instance = new GetSolWashTradeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSolWashTradeRequest
        /// </summary>
        [Fact]
        public void GetSolWashTradeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSolWashTradeRequest
            //Assert.IsType<GetSolWashTradeRequest>(instance);
        }


        /// <summary>
        /// Test the property 'FirstSignature'
        /// </summary>
        [Fact]
        public void FirstSignatureTest()
        {
            // TODO unit test for the property 'FirstSignature'
        }

    }

}
