/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetSolCustomTokenRiskRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSolCustomTokenRiskRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSolCustomTokenRiskRequest
        //private GetSolCustomTokenRiskRequest instance;

        public GetSolCustomTokenRiskRequestTests()
        {
            // TODO uncomment below to create an instance of GetSolCustomTokenRiskRequest
            //instance = new GetSolCustomTokenRiskRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSolCustomTokenRiskRequest
        /// </summary>
        [Fact]
        public void GetSolCustomTokenRiskRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSolCustomTokenRiskRequest
            //Assert.IsType<GetSolCustomTokenRiskRequest>(instance);
        }


        /// <summary>
        /// Test the property 'MintAddress'
        /// </summary>
        [Fact]
        public void MintAddressTest()
        {
            // TODO unit test for the property 'MintAddress'
        }
        /// <summary>
        /// Test the property 'HoldingPeriod'
        /// </summary>
        [Fact]
        public void HoldingPeriodTest()
        {
            // TODO unit test for the property 'HoldingPeriod'
        }
        /// <summary>
        /// Test the property 'TokenId'
        /// </summary>
        [Fact]
        public void TokenIdTest()
        {
            // TODO unit test for the property 'TokenId'
        }
        /// <summary>
        /// Test the property 'Dist'
        /// </summary>
        [Fact]
        public void DistTest()
        {
            // TODO unit test for the property 'Dist'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'RiskFreeRate'
        /// </summary>
        [Fact]
        public void RiskFreeRateTest()
        {
            // TODO unit test for the property 'RiskFreeRate'
        }
        /// <summary>
        /// Test the property 'WinsOutliers'
        /// </summary>
        [Fact]
        public void WinsOutliersTest()
        {
            // TODO unit test for the property 'WinsOutliers'
        }
        /// <summary>
        /// Test the property 'Frequency'
        /// </summary>
        [Fact]
        public void FrequencyTest()
        {
            // TODO unit test for the property 'Frequency'
        }
        /// <summary>
        /// Test the property 'ReptCurr'
        /// </summary>
        [Fact]
        public void ReptCurrTest()
        {
            // TODO unit test for the property 'ReptCurr'
        }
        /// <summary>
        /// Test the property 'ExcludeWash'
        /// </summary>
        [Fact]
        public void ExcludeWashTest()
        {
            // TODO unit test for the property 'ExcludeWash'
        }
        /// <summary>
        /// Test the property 'Drawdown'
        /// </summary>
        [Fact]
        public void DrawdownTest()
        {
            // TODO unit test for the property 'Drawdown'
        }
        /// <summary>
        /// Test the property 'ArcParams'
        /// </summary>
        [Fact]
        public void ArcParamsTest()
        {
            // TODO unit test for the property 'ArcParams'
        }
        /// <summary>
        /// Test the property 'GarParams'
        /// </summary>
        [Fact]
        public void GarParamsTest()
        {
            // TODO unit test for the property 'GarParams'
        }
        /// <summary>
        /// Test the property 'HarParams'
        /// </summary>
        [Fact]
        public void HarParamsTest()
        {
            // TODO unit test for the property 'HarParams'
        }

    }

}
